### ISSUE TITLE
Delicious being acquired by Pinboard, forced export no longer needed/recommended?

### ISSUE THREAD

**Issue by lazerhawk** [szafranek/delicious-exporter#11]
Since up until now Delicious seemed to be on deathwatch autopilot, violating the ToS with this exporter was somewhat acceptable, but it appears Delicious will be saved in a read-only state on June 15/2017 and conventional export should work again...

[https://blog.pinboard.in/2017/06/pinboard_acquires_delicious/](url)

**Comment by u4842** [comment]
Their exporter isn't available as far as I can see. https://del.icio.us/export

> We're sorry, but due to heavy load on our database we are no longer able to offer an export function. Our engineers are working on this and we will restore it as soon as possible.

**Comment by lazerhawk** [comment]
That's the old export disabled message that's been up for months. Matej of Pinboard seems to be saying that after switching over to read only mode on 6/15 he will reenable export after fiddling with the codebase a bit to make hosting cheaper ($4K monthly AWS bill currently!?!)

**Comment by lazerhawk** [comment]
Native export is now live! Check it to make sure it isn't messed up!

**Comment by szafranek** [comment]
I decided to keep the source on github. However, I updated the readme, so it it now recommends using the native export function instead.
