### ISSUE TITLE
The --validate flag does not seem to work

### ISSUE THREAD

**Issue by alekdavis** [szafranek/delicious-exporter#4]
Running the tool with the --validate option causes the following errors:

Server not found | <URL>
'head' is not recognized as an internal or external command,
operable program or batch file.

Out of thousands of bookmarks  I have, the export attempt with the --validate flag returned only two valid links.

**Comment by Yggdrasil** [comment]
That's weird. It worked for me today, except for a few servers being incorrectly reported as 'not found'.

On which Operating System are you running the export? What's the output if you run `which head` in a terminal?

**Comment by alekdavis** [comment]
I'm running it on Windows 10. I already uninstalled all the components, so can't rerun it, but the weird thing was that it handled the first couple of links, and then just failed an the rest of them. I'm wondering if it was a timing issue, but it's not like there was an internet outage.

**Comment by szafranek** [comment]
I'm closing it since there wasn't any follow up.
