### ISSUE TITLE
Error while exporting

### ISSUE THREAD

**Issue by arondeparon** [szafranek/delicious-exporter#9]
The following error occurs after the export is running for a while. Used command:

`./export.rb -u <username> -p <password> -o bookmarks.html`

> ./export.rb:74:in `url': undefined method `[]' for nil:NilClass (NoMethodError)
>         from ./export.rb:165:in `block (2 levels) in bookmarks_string'
>         from /Users/aron/.rvm/gems/ruby-2.4.0@global/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
>         from /Users/aron/.rvm/gems/ruby-2.4.0@global/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
>         from /Users/aron/.rvm/gems/ruby-2.4.0@global/gems/nokogiri-1.7.0.1/lib/nokogiri/xml/node_set.rb:186:in `each'
>         from ./export.rb:164:in `block in bookmarks_string'
>         from ./export.rb:161:in `each'
>         from ./export.rb:161:in `bookmarks_string'
>         from ./export.rb:211:in `<main>'

**Comment by szafranek** [comment]
See the PR #10 discussion for details.
